version : ’3.8 ’
 services :
 backend :
 build : ./ backend
 ports :
 - "3000:3000"
 environment :
 - MONGODB_URI = mongodb :// mongo :27017/ mydb
 depends_on :
 - mongo
 volumes :
 - ./ backend :/ app
 - / app / node_modules

 mongo :
 image : mongo :5

 ports :
 - "27017:27017"
 volumes :
 - mongo_data :/ data / db

 volumes :
 mongo_data :
