version: '3.8'

services:
  oracle:
    image: container.oracle.com/database/express:latest
    container_name: oracle-db
    ports:
      - 1521:1521
    environment:
      ORACLE_PWD: Lopez#880
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle-data: {}
